### ISSUE TITLE
Use awful.spawn.with_shell instead of os.execute

### ISSUE THREAD

**Issue by ODenisov** [carlosecp/awesome#1]
os.execute is a blocking operation, you need to avoid using it.
May I suggest using __awful.spawn.with_shell__ or __awful.spawn.easy_async_with_shell__ instead
For more info check out https://awesomewm.org/apidoc/libraries/awful.spawn.html

**Comment by carlosecp** [comment]
Yeah you are right, I see now. 

In this case, I did have those commands spawned with `awful.spawn` (just `spawn`, not `spawn.with_shell`), but noticed that it was like awesome was expecting some GUI app to spawn when using that command, so after raising the volume for example, awesome got stuck with the "loading" cursor pointer. It seems like this doesn't happend with `os.execute`, that's why I changed this. Example below:
![image](https://user-images.githubusercontent.com/47466248/185495773-5a9edfb9-ccd2-4dc8-b8cd-b367df6c5b65.png)

I'm gonna chage it to `awful.spawn.with_shell` then, this doesn't have that behaviour that `awful.spawn` did. Thanks.
